### PR TITLE
chore: remove old signalk role

### PR DESCRIPTION
**Pull request by tkurki**
Use signalk-npm instead.

### CODE REVIEW

**Comment by bergie** [comment]
Fixes #77 I believe

**Comment by bhavers** [comment]
What is the role node-app? Seems like it is similar to the signalk role and also pulling from git and installing in /opt. Should this also be removed?

**Comment by tkurki** [comment]
node-app is what is says on the tin: a generic node-app. I believe at least @chacal is using it.

**Comment by hkapanen** [comment]
I'm using the role node-app as well.

**Pull request merged**
